### ISSUE TITLE
"./launch_here.rb:17:in `<main>': undefined method `exists?' for File:Class (NoMethodError)..."

### ISSUE THREAD

**Issue by antdude** [ruby-rbot/rbot#88]
Unable to launch rbot after upgrading Fedora to v39 with https://github.com/ruby-rbot/rbot/archive/master.zip:

$ /usr/bin/ruby-mri ./launch_here.rb
Running from /home/ant/Downloads/rbot-master
./launch_here.rb:17:in `<main>': undefined method `exists?' for File:Class (NoMethodError)

  if File.exists? '.git'
         ^^^^^^^^
Did you mean?  exist?

**Comment by henk84** [comment]
This should be fixed with commit 76a7d922b.
Could you test it, please?

**Comment by antdude** [comment]
`$ time git clone https://github.com/ruby-rbot/rbot.git
Cloning into 'rbot'...
remote: Enumerating objects: 18837, done.
remote: Counting objects: 100% (269/269), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 18837 (delta 144), reused 134 (delta 117), pack-reused 18568 (from 3)
Receiving objects: 100% (18837/18837), 7.79 MiB | 20.73 MiB/s, done.
Resolving deltas: 100% (9992/9992), done.

real    0m1.164s
user    0m0.851s
sys     0m0.387s
$ cd rbot
$ /usr/bin/ruby-mri ./launch_here.rb
Running from /home/ant/bin/rbot
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require':
/home/ant/bin/rbot/lib/rbot/load-gettext.rb:69: Invalid retry after ensure (SyntaxError)
    retry
    ^~~~~

        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/ant/bin/rbot/lib/rbot/ircbot.rb:42:in `<top (required)>'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/ant/bin/rbot/bin/rbot:90:in `<top (required)>'
        from ./launch_here.rb:68:in `load'
        from ./launch_here.rb:68:in `<main>'
`

**Comment by henk84** [comment]
> $ /usr/bin/ruby-mri ./launch_here.rb

AFAIU from https://en.wikipedia.org/wiki/Ruby_MRI `ruby-mri` had its last release in 2008, so around 17 years ago, and does not seem to be developed anymore.

> $ /usr/bin/ruby-mri ./launch_here.rb
> Running from /home/ant/bin/rbot
> <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:136:in `require':
> /home/ant/bin/rbot/lib/rbot/load-gettext.rb:69: Invalid retry after ensure (SyntaxError)
>     retry

I can’t make sense of this error. There is no `ensure` in that context at all and I don’t see anything wrong with that code.

Given that and the fact that `ruby-mri` seems very old and unmaintained, I tend to think the problem is not my lack of ruby skill (which is certainly the case).
Can you check with a different ruby interpreter, maybe one that’s less than a decade old?
